using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Linq;
using System.Text;

/*
namespace AcClient {
    public enum CallbackLoseFocusResult : uint {
        lfBlock = 0x0,
        lfTransfer = 0x1,
    };
    public enum BlitMode : uint {
        Blit_Normal = 0x0,
        Blit_3Alpha = 0x1,
        Blit_4Alpha = 0x2,
        Blit_Colorize = 0x3,
        Blit_Multiply = 0x4,
        Blit_Screen = 0x5,
        Blit_Grayscale = 0x6,
        Blit_NOP = 0x7,
        Blit_nModes = 0x8,
    };
    public enum BorderLocation : uint {
        BORDER_NONE = 0x0,
        BORDER_UL = 0x1,
        BORDER_TOP = 0x2,
        BORDER_UR = 0x3,
        BORDER_RIGHT = 0x4,
        BORDER_LR = 0x5,
        BORDER_BOTTOM = 0x6,
        BORDER_LL = 0x7,
        BORDER_LEFT = 0x8,
    };
    public enum AsyncResult : uint {
        AsyncResult_Unknown = 0x0,
        AsyncResult_Success = 0x1,
        AsyncResult_PartialSuccess = 0x2,
        AsyncResult_Failure = 0x3,
    };
    public enum PropertyInheritanceType__Type : uint {
        ClassOnly = 0x0,
        InstanceOnly = 0x1,
        Either = 0x2,
    };
    public enum PropertyDatFileType__Type : uint {
        ClientOnlyData = 0x0,
        ServerOnlyData = 0x1,
        SharedData = 0x2,
    };
    public enum PropertyPropagationType__Type : uint {
        NetPredictedSharedVisually = 0x0,
        NetPredictedSharedPrivately = 0x1,
        NetSharedVisually = 0x2,
        NetSharedPrivately = 0x3,
        NetNotShared = 0x4,
        WorldSharedWithServers = 0x5,
        WorldSharedWithServersAndClients = 0x6,
    };
    public enum PropertyCachingType__Type : uint {
        Global = 0x0,
        Internal = 0x1,
    };
    public enum TSRecvMode : uint {
        TSRECV_BLOCK = 0x0,
        TSRECV_LATESTONLY = 0x1,
        FORCE_TSRecvMode_32_BIT = 0x7FFFFFFF,
    };
    public enum NetBlob__State : uint {
        NETBLOB_FROZEN = 0x0,
        NETBLOB_SENDING = 0x1,
        NETBLOB_RECEIVING = 0x2,
        NETBLOB_RECEIVED = 0x3,
        NETBLOB_FRAGMENTED = 0x4,
        FORCE_State_32_BIT = 0x7FFFFFFF,
    };
    public enum PowerBarMode {
        PBM_UNDEF = 0x0,
        PBM_COMBAT = 0x1,
        PBM_ADVANCED_COMBAT = 0x2,
        PBM_JUMP = 0x3,
        PBM_DDD = 0x4,
    };

    public enum HoldKey : uint {
        Invalid = 0x0,
        None = 0x1,
        Run = 0x2,
    };

    public enum ATTACK_HEIGHT : uint {
        UNDEF_ATTACK_HEIGHT = 0x0,
        HIGH_ATTACK_HEIGHT = 0x1,
        MEDIUM_ATTACK_HEIGHT = 0x2,
        LOW_ATTACK_HEIGHT = 0x3,
    };
    public enum UIElementType : uint {
        SBOX = 0x1000049A,
        CHAT = 0x10000601,
        FCH1 = 0x10000505,
        FCH2 = 0x1000050E,
        FCH3 = 0x1000050F,
        FCH4 = 0x10000510,
        EXAM = 0x100005F7,
        VITS = 0x100005FA,
        SVIT = 0x100006D5,
        ENVP = 0x100005FD,
        PANS = 0x100005FF,
        TBAR = 0x10000603,
        INDI = 0x10000611,
        PBAR = 0x10000613,
        COMB = 0x100006B5,
        RADA = 0x100006D2,
    }
    public enum MovementTypes : uint {
        Invalid = 0x0,
        RawCommand = 0x1,
        InterpretedCommand = 0x2,
        StopRawCommand = 0x3,
        StopInterpretedCommand = 0x4,
        StopCompletely = 0x5,
        MoveToObject = 0x6,
        MoveToPosition = 0x7,
        TurnToObject = 0x8,
        TurnToHeading = 0x9,
    };
    public enum NameType : uint {
        NAME_SINGULAR = 0x0,
        NAME_PLURAL = 0x1,
        NAME_APPROPRIATE = 0x2,
    };

    public enum ConfirmationType : uint {
        UNDEF = 0x0,
        ALLEGIANCE_SWEAR = 0x1,
        ALTER_SKILL = 0x2,
        ALTER_ATTRIBUTE = 0x3,
        FELLOWSHIP_RECRUIT = 0x4,
        CRAFT_INTERACTION = 0x5,
        USE_AUGMENTATION = 0x6,
        YESNO = 0x7,
    };


    public enum COMBAT_MODE : uint {
        UNDEF = 0x0,
        NONCOMBAT = 0x1,
        MELEE = 0x2,
        MISSILE = 0x4,
        MAGIC = 0x8,
        COMBAT = 0xE,
    };

    public enum ITEM_TYPE : uint {
        TYPE_UNDEF = 0x0,
        TYPE_MELEE_WEAPON = 0x1,
        TYPE_ARMOR = 0x2,
        TYPE_CLOTHING = 0x4,
        TYPE_JEWELRY = 0x8,
        TYPE_CREATURE = 0x10,
        TYPE_FOOD = 0x20,
        TYPE_MONEY = 0x40,
        TYPE_MISC = 0x80,
        TYPE_MISSILE_WEAPON = 0x100,
        TYPE_CONTAINER = 0x200,
        TYPE_USELESS = 0x400,
        TYPE_GEM = 0x800,
        TYPE_SPELL_COMPONENTS = 0x1000,
        TYPE_WRITABLE = 0x2000,
        TYPE_KEY = 0x4000,
        TYPE_CASTER = 0x8000,
        TYPE_PORTAL = 0x10000,
        TYPE_LOCKABLE = 0x20000,
        TYPE_PROMISSORY_NOTE = 0x40000,
        TYPE_MANASTONE = 0x80000,
        TYPE_SERVICE = 0x100000,
        TYPE_MAGIC_WIELDABLE = 0x200000,
        TYPE_CRAFT_COOKING_BASE = 0x400000,
        TYPE_CRAFT_ALCHEMY_BASE = 0x800000,
        TYPE_CRAFT_FLETCHING_BASE = 0x1000000,
        TYPE_CRAFT_ALCHEMY_INTERMEDIATE = 0x4000000,
        TYPE_CRAFT_FLETCHING_INTERMEDIATE = 0x8000000,
        TYPE_LIFESTONE = 0x10000000,
        TYPE_TINKERING_TOOL = 0x20000000,
        TYPE_TINKERING_MATERIAL = 0x40000000,
        TYPE_GAMEBOARD = 0x80000000,
        TYPE_PORTAL_MAGIC_TARGET = 0x10010000,
        TYPE_LOCKABLE_MAGIC_TARGET = 0x280,
        TYPE_VESTEMENTS = 0x6,
        TYPE_WEAPON = 0x101,
        TYPE_WEAPON_OR_CASTER = 0x8101,
        TYPE_ITEM = 0x2DFBEF,
        TYPE_REDIRECTABLE_ITEM_ENCHANTMENT_TARGET = 0x8107,
        TYPE_ITEM_ENCHANTABLE_TARGET = 0x88B8F,
        TYPE_SELF = 0x0,
        TYPE_VENDOR_SHOPKEEP = 0x480467A7,
        TYPE_VENDOR_GROCER = 0x446220,
    };

    public enum INVENTORY_LOC : uint {
        NONE_LOC = 0x0,
        HEAD_WEAR_LOC = 0x1,
        CHEST_WEAR_LOC = 0x2,
        ABDOMEN_WEAR_LOC = 0x4,
        UPPER_ARM_WEAR_LOC = 0x8,
        LOWER_ARM_WEAR_LOC = 0x10,
        HAND_WEAR_LOC = 0x20,
        UPPER_LEG_WEAR_LOC = 0x40,
        LOWER_LEG_WEAR_LOC = 0x80,
        FOOT_WEAR_LOC = 0x100,
        CHEST_ARMOR_LOC = 0x200,
        ABDOMEN_ARMOR_LOC = 0x400,
        UPPER_ARM_ARMOR_LOC = 0x800,
        LOWER_ARM_ARMOR_LOC = 0x1000,
        UPPER_LEG_ARMOR_LOC = 0x2000,
        LOWER_LEG_ARMOR_LOC = 0x4000,
        NECK_WEAR_LOC = 0x8000,
        WRIST_WEAR_LEFT_LOC = 0x10000,
        WRIST_WEAR_RIGHT_LOC = 0x20000,
        FINGER_WEAR_LEFT_LOC = 0x40000,
        FINGER_WEAR_RIGHT_LOC = 0x80000,
        MELEE_WEAPON_LOC = 0x100000,
        SHIELD_LOC = 0x200000,
        MISSILE_WEAPON_LOC = 0x400000,
        MISSILE_AMMO_LOC = 0x800000,
        HELD_LOC = 0x1000000,
        TWO_HANDED_LOC = 0x2000000,
        TRINKET_ONE_LOC = 0x4000000,
        CLOAK_LOC = 0x8000000,
        SIGIL_ONE_LOC = 0x10000000,
        SIGIL_TWO_LOC = 0x20000000,
        SIGIL_THREE_LOC = 0x40000000,
        CLOTHING_LOC = 0x80001FF,
        ARMOR_LOC = 0x7E00,
        JEWELRY_LOC = 0x7C0F8000,
        WRIST_WEAR_LOC = 0x30000,
        FINGER_WEAR_LOC = 0xC0000,
        SIGIL_LOC = 0x70000000,
        READY_SLOT_LOC = 0x3F00000,
        WEAPON_LOC = 0x2500000,
        WEAPON_READY_SLOT_LOC = 0x3500000,
        ALL_LOC = 0x7FFFFFFF,
        CAN_GO_IN_READY_SLOT_LOC = 0x7FFFFFFF,
    };
    public enum ITEM_USEABLE : uint {
        USEABLE_UNDEF = 0x0,
        USEABLE_NO = 0x1,
        USEABLE_SELF = 0x2,
        USEABLE_WIELDED = 0x4,
        USEABLE_CONTAINED = 0x8,
        USEABLE_VIEWED = 0x10,
        USEABLE_REMOTE = 0x20,
        USEABLE_NEVER_WALK = 0x40,
        USEABLE_OBJSELF = 0x80,
        USEABLE_CONTAINED_VIEWED = 0x18,
        USEABLE_CONTAINED_VIEWED_REMOTE = 0x38,
        USEABLE_CONTAINED_VIEWED_REMOTE_NEVER_WALK = 0x78,
        USEABLE_VIEWED_REMOTE = 0x30,
        USEABLE_VIEWED_REMOTE_NEVER_WALK = 0x70,
        USEABLE_REMOTE_NEVER_WALK = 0x60,
        USEABLE_SOURCE_WIELDED_TARGET_WIELDED = 0x40004,
        USEABLE_SOURCE_WIELDED_TARGET_CONTAINED = 0x80004,
        USEABLE_SOURCE_WIELDED_TARGET_VIEWED = 0x100004,
        USEABLE_SOURCE_WIELDED_TARGET_REMOTE = 0x200004,
        USEABLE_SOURCE_WIELDED_TARGET_REMOTE_NEVER_WALK = 0x600004,
        USEABLE_SOURCE_CONTAINED_TARGET_WIELDED = 0x40008,
        USEABLE_SOURCE_CONTAINED_TARGET_CONTAINED = 0x80008,
        USEABLE_SOURCE_CONTAINED_TARGET_OBJSELF_OR_CONTAINED = 0x880008,
        USEABLE_SOURCE_CONTAINED_TARGET_SELF_OR_CONTAINED = 0xA0008,
        USEABLE_SOURCE_CONTAINED_TARGET_VIEWED = 0x100008,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE = 0x200008,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_NEVER_WALK = 0x600008,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_OR_SELF = 0x220008,
        USEABLE_SOURCE_VIEWED_TARGET_WIELDED = 0x40010,
        USEABLE_SOURCE_VIEWED_TARGET_CONTAINED = 0x80010,
        USEABLE_SOURCE_VIEWED_TARGET_VIEWED = 0x100010,
        USEABLE_SOURCE_VIEWED_TARGET_REMOTE = 0x200010,
        USEABLE_SOURCE_REMOTE_TARGET_WIELDED = 0x40020,
        USEABLE_SOURCE_REMOTE_TARGET_CONTAINED = 0x80020,
        USEABLE_SOURCE_REMOTE_TARGET_VIEWED = 0x100020,
        USEABLE_SOURCE_REMOTE_TARGET_REMOTE = 0x200020,
        USEABLE_SOURCE_REMOTE_TARGET_REMOTE_NEVER_WALK = 0x600020,
        USEABLE_SOURCE_MASK = 0xFFFF,
        USEABLE_TARGET_MASK = 0xFFFF0000,
    };

    public enum COMBAT_USE : uint {
        COMBAT_USE_NONE = 0x0,
        COMBAT_USE_MELEE = 0x1,
        COMBAT_USE_MISSILE = 0x2,
        COMBAT_USE_AMMO = 0x3,
        COMBAT_USE_SHIELD = 0x4,
        COMBAT_USE_TWO_HANDED = 0x5,
    };
    public enum AMMO_TYPE : uint {
        AMMO_NONE = 0x0,
        AMMO_ARROW = 0x1,
        AMMO_BOLT = 0x2,
        AMMO_ATLATL = 0x4,
        AMMO_ARROW_CRYSTAL = 0x8,
        AMMO_BOLT_CRYSTAL = 0x10,
        AMMO_ATLATL_CRYSTAL = 0x20,
        AMMO_ARROW_CHORIZITE = 0x40,
        AMMO_BOLT_CHORIZITE = 0x80,
        AMMO_ATLATL_CHORIZITE = 0x100,
    };
    public enum PositionState : uint {
        IN_3D_VIEW = 0x0,
        WIELDED = 0x1,
        IN_CONTAINER = 0x2,
        BEING_REMOVED = 0x3,
    };
    public enum RadarEnum : uint {
        Undef = 0x0,
        ShowNever = 0x1,
        ShowMovement = 0x2,
        ShowAttacking = 0x3,
        ShowAlways = 0x4,
    };
    public enum DetectionType : uint {
        NoChange = 0x0,
        Entered = 0x1,
        Leftn = 0x2,
    };
    public enum PhysicsState : uint {
        STATIC_PS = 0x1,
        UNUSED1_PS = 0x2,
        ETHEREAL_PS = 0x4,
        REPORT_COLLISIONS_PS = 0x8,
        IGNORE_COLLISIONS_PS = 0x10,
        NODRAW_PS = 0x20,
        MISSILE_PS = 0x40,
        PUSHABLE_PS = 0x80,
        ALIGNPATH_PS = 0x100,
        PATHCLIPPED_PS = 0x200,
        GRAVITY_PS = 0x400,
        LIGHTING_ON_PS = 0x800,
        PARTICLE_EMITTER_PS = 0x1000,
        UNNUSED2_PS = 0x2000,
        HIDDEN_PS = 0x4000,
        SCRIPTED_COLLISION_PS = 0x8000,
        HAS_PHYSICS_BSP_PS = 0x10000,
        INELASTIC_PS = 0x20000,
        HAS_DEFAULT_ANIM_PS = 0x40000,
        HAS_DEFAULT_SCRIPT_PS = 0x80000,
        CLOAKED_PS = 0x100000,
        REPORT_COLLISIONS_AS_ENVIRONMENT_PS = 0x200000,
        EDGE_SLIDE_PS = 0x400000,
        SLEDDING_PS = 0x800000,
        FROZEN_PS = 0x1000000,
    };
    public enum SurfaceHandlerEnum : uint {
        SH_UNKNOWN = 0x0,
        SH_DATABASE = 0x1,
        SH_PALSHIFT = 0x2,
        SH_TEXMERGE = 0x3,
        SH_CUSTOMDB = 0x4,
        NUM_SURFACE_HANDLER = 0x5,
    };
    public enum PixelFormatID : uint {
        PFID_UNKNOWN = 0x0,
        PFID_R8G8B8 = 0x14,
        PFID_A8R8G8B8 = 0x15,
        PFID_X8R8G8B8 = 0x16,
        PFID_R5G6B5 = 0x17,
        PFID_X1R5G5B5 = 0x18,
        PFID_A1R5G5B5 = 0x19,
        PFID_A4R4G4B4 = 0x1A,
        PFID_R3G3B2 = 0x1B,
        PFID_A8 = 0x1C,
        PFID_A8R3G3B2 = 0x1D,
        PFID_X4R4G4B4 = 0x1E,
        PFID_A2B10G10R10 = 0x1F,
        PFID_A8B8G8R8 = 0x20,
        PFID_X8B8G8R8 = 0x21,
        PFID_A2R10G10B10 = 0x23,
        PFID_A8P8 = 0x28,
        PFID_P8 = 0x29,
        PFID_L8 = 0x32,
        PFID_A8L8 = 0x33,
        PFID_A4L4 = 0x34,
        PFID_V8U8 = 0x3C,
        PFID_L6V5U5 = 0x3D,
        PFID_X8L8V8U8 = 0x3E,
        PFID_Q8W8V8U8 = 0x3F,
        PFID_V16U16 = 0x40,
        PFID_A2W10V10U10 = 0x43,
        PFID_UYVY = 0x59565955,
        PFID_R8G8_B8G8 = 0x47424752,
        PFID_YUY2 = 0x32595559,
        PFID_G8R8_G8B8 = 0x42475247,
        PFID_DXT1 = 0x31545844,
        PFID_DXT2 = 0x32545844,
        PFID_DXT3 = 0x33545844,
        PFID_DXT4 = 0x34545844,
        PFID_DXT5 = 0x35545844,
        PFID_D16_LOCKABLE = 0x46,
        PFID_D32 = 0x47,
        PFID_D15S1 = 0x49,
        PFID_D24S8 = 0x4B,
        PFID_D24X8 = 0x4D,
        PFID_D24X4S4 = 0x4F,
        PFID_D16 = 0x50,
        PFID_VERTEXDATA = 0x64,
        PFID_INDEX16 = 0x65,
        PFID_INDEX32 = 0x66,
        PFID_CUSTOM_R8G8B8A8 = 0xF0,
        PFID_CUSTOM_A8B8G8R8 = 0xF1,
        PFID_CUSTOM_B8G8R8 = 0xF2,
        PFID_CUSTOM_LSCAPE_R8G8B8 = 0xF3,
        PFID_CUSTOM_LSCAPE_ALPHA = 0xF4,
        PFID_CUSTOM_RAW_JPEG = 0x1F4,
        PFID_CUSTOM_FIRST = 0xF0,
        PFID_CUSTOM_LAST = 0x1F4,
        PFID_INVALID = 0x7FFFFFFF,
    };

    public enum TextureType : uint {
        TEXTURETYPE_UNDEFINED = 0x1,
        TEXTURETYPE_2D = 0x2,
        TEXTURETYPE_3D = 0x3,
        TEXTURETYPE_CUBE = 0x4,
        TEXTURETYPE_MOVIE2D = 0x5,
    };
    public enum VertexType : uint {
        UnknownVertexType = 0x0,
        CSWVertexType = 0x1,
    };
    public enum PrimType : uint {
        PRIMTYPE_POINTLIST = 0x1,
        PRIMTYPE_LINELIST = 0x2,
        PRIMTYPE_LINESTRIP = 0x3,
        PRIMTYPE_TRIANGLELIST = 0x4,
        PRIMTYPE_TRIANGLESTRIP = 0x5,
        PRIMTYPE_TRIANGLEFAN = 0x6,
    };
    public enum LayerModType : uint {
        LAYERMOD_UVTRANSLATE = 0x1,
        LAYERMOD_UVROTATE = 0x2,
        LAYERMOD_UVSCALE = 0x3,
        LAYERMOD_UVTRANSFORM = 0x4,
        LAYERMOD_INVALID = 0x5,
    };
    public enum TextureOp : uint {
        TEXOP_DISABLE = 0x1,
        TEXOP_SELECTARG1 = 0x2,
        TEXOP_SELECTARG2 = 0x3,
        TEXOP_MODULATE = 0x4,
        TEXOP_MODULATE2X = 0x5,
        TEXOP_MODULATE4X = 0x6,
        TEXOP_ADD = 0x7,
        TEXOP_ADDSIGNED = 0x8,
        TEXOP_ADDSIGNED2X = 0x9,
        TEXOP_SUBTRACT = 0xA,
        TEXOP_ADDSMOOTH = 0xB,
        TEXOP_BLENDDIFFUSEALPHA = 0xC,
        TEXOP_BLENDTEXTUREALPHA = 0xD,
        TEXOP_BLENDFACTORALPHA = 0xE,
        TEXOP_BLENDTEXTUREALPHAPM = 0xF,
        TEXOP_BLENDCURRENTALPHA = 0x10,
        TEXOP_PREMODULATE = 0x11,
        TEXOP_MODULATEALPHA_ADDCOLOR = 0x12,
        TEXOP_MODULATECOLOR_ADDALPHA = 0x13,
        TEXOP_MODULATEINVALPHA_ADDCOLOR = 0x14,
        TEXOP_MODULATEINVCOLOR_ADDALPHA = 0x15,
        TEXOP_BUMPENVMAP = 0x16,
        TEXOP_BUMPENVMAPLUMINANCE = 0x17,
        TEXOP_DOTPRODUCT3 = 0x18,
        TEXOP_MULTIPLYADD = 0x19,
        TEXOP_LERP = 0x1A,
        TEXOP_INVALID = 0x7FFFFFFF,
    };

    public enum TexAddress : uint {
        TEXADDRESS_WRAP = 0x1,
        TEXADDRESS_MIRROR = 0x2,
        TEXADDRESS_CLAMP = 0x3,
        TEXADDRESS_BORDER = 0x4,
        TEXADDRESS_MIRRORONCE = 0x5,
        TEXADDRESS_INVALID = 0x7FFFFFFF,
    };
    public enum TexFilterMode : uint {
        TEXFILTER_NONE = 0x0,
        TEXFILTER_POINT = 0x1,
        TEXFILTER_LINEAR = 0x2,
        TEXFILTER_ANISOTROPIC = 0x3,
        TEXFILTER_PYRAMIDALQUAD = 0x6,
        TEXFILTER_GAUSSIANQUAD = 0x7,
        TEXFILTER_INVALID = 0x7FFFFFFF,
    };
    public enum DepthTestMode : uint {
        DEPTHTEST_NEVER = 0x1,
        DEPTHTEST_LESS = 0x2,
        DEPTHTEST_EQUAL = 0x3,
        DEPTHTEST_LESSEQUAL = 0x4,
        DEPTHTEST_GREATER = 0x5,
        DEPTHTEST_NOTEQUAL = 0x6,
        DEPTHTEST_GREATEREQUAL = 0x7,
        DEPTHTEST_ALWAYS = 0x8,
        DEPTHTEST_INVALID = 0x7FFFFFFF,
    };
    public enum CullModeType : uint {
        CULLMODE_NONE = 0x1,
        CULLMODE_CW = 0x2,
        CULLMODE_CCW = 0x3,
        CULLMODE_INVALID = 0x7FFFFFFF,
    };
    public enum FillModeType : uint {
        FILLMODE_POINT = 0x1,
        FILLMODE_WIREFRAME = 0x2,
        FILLMODE_SOLID = 0x3,
        FILLMODE_INVALID = 0x7FFFFFFF,
    };
    public enum BlendOpType : uint {
        BLENDOP_ADD = 0x1,
        BLENDOP_SUBTRACT = 0x2,
        BLENDOP_REVSUBTRACT = 0x3,
        BLENDOP_MIN = 0x4,
        BLENDOP_MAX = 0x5,
        BLENDOP_INVALID = 0x7FFFFFFF,
    };
    public enum BlendMode : uint {
        BLEND_ZERO = 0x1,
        BLEND_ONE = 0x2,
        BLEND_SRCCOLOR = 0x3,
        BLEND_INVSRCCOLOR = 0x4,
        BLEND_SRCALPHA = 0x5,
        BLEND_INVSRCALPHA = 0x6,
        BLEND_DSTALPHA = 0x7,
        BLEND_INVDSTALPHA = 0x8,
        BLEND_DSTCOLOR = 0x9,
        BLEND_INVDSTCOLOR = 0xA,
        BLEND_SRCALPHASAT = 0xB,
        BLEND_BOTHSRCALPHA = 0xC,
        BLEND_BOTHINVSRCALPHA = 0xD,
        BLEND_BLENDFACTOR = 0xE,
        BLEND_INVBLENDFACTOR = 0xF,
        BLEND_INVALID = 0x7FFFFFFF,
    };
    public enum ShaderVersionType : uint {
        ShaderVersion_1_1 = 0x0,
        ShaderVersion_2_0 = 0x1,
        ShaderVersion_MaxVersions = 0x2,
        ShaderVersion_Invalid = 0x3,
    };
    public enum Render__LightingType : uint {
        DYNAMIC_LIGHTING = 0x0,
        STATIC_LIGHTING = 0x1,
        FULL_LIGHTING = 0x2,
        FORCE_LightingType_32_BIT = 0x7FFFFFFF,
    };
    public enum WaveformType : uint {
        WAVEFORM_INVALID = 0x0,
        WAVEFORM_NONE = 0x1,
        WAVEFORM_SPEED = 0x2,
        WAVEFORM_NOISE = 0x3,
        WAVEFORM_SINE = 0x4,
        WAVEFORM_SQUARE = 0x5,
        WAVEFORM_BOUNCE = 0x6,
        WAVEFORM_PERLIN = 0x7,
        WAVEFORM_FRACTAL = 0x8,
        WAVEFORM_FRAMELOOP = 0x9,
        NUM_WAVEFORMS = 0xA,
    };
    public enum RMDataType : uint {
        RMDATA_WAVEFORM = 0x3E8,
        RMDATA_COLOR = 0x7D0,
        RMDATA_TEXTURE = 0xBB8,
        RMDATA_BOOL = 0xFA0,
        RMDATA_TEXTURE_PTR = 0x2710,
        RMDATA_INVALID = 0x7FFFFFFF,
    };
    public enum RMFieldType : uint {
        RMFIELD_LAYER_DIFFUSE = 0x0,
        RMFIELD_LAYER_SPECULAR = 0x1,
        RMFIELD_LAYER_SPECULARPOWER = 0x2,
        RMFIELD_LAYER_DYE = 0x3,
        RMFIELD_LAYER_CULLMODE = 0x4,
        RMFIELD_LAYER_DEPTHTEST = 0x5,
        RMFIELD_LAYER_DEPTHWRITE = 0x6,
        RMFIELD_LAYER_ALPHATEST = 0x7,
        RMFIELD_LAYER_ALPHATESTREF = 0x8,
        RMFIELD_LAYER_STAGE_TEXTURE = 0x9,
        RMFIELD_LAYER_STAGE_ADDRESSMODEU = 0xA,
        RMFIELD_LAYER_STAGE_ADDRESSMODEV = 0xB,
        RMFIELD_LAYER_MOD_ORIGIN_XTRANSLATE = 0xC,
        RMFIELD_LAYER_MOD_ORIGIN_YTRANSLATE = 0xD,
        RMFIELD_LAYER_MOD_ORIGIN_ZTRANSLATE = 0xE,
        RMFIELD_LAYER_MOD_ORIGIN_XSCALE = 0xF,
        RMFIELD_LAYER_MOD_ORIGIN_YSCALE = 0x10,
        RMFIELD_LAYER_MOD_ORIGIN_ZSCALE = 0x11,
        RMFIELD_LAYER_MOD_ORIGIN_ORIGINPHASE = 0x12,
        RMFIELD_LAYER_MOD_ORIGIN_NORMALPHASE = 0x13,
        RMFIELD_LAYER_MOD_NORMAL_XTRANSLATE = 0x14,
        RMFIELD_LAYER_MOD_NORMAL_YTRANSLATE = 0x15,
        RMFIELD_LAYER_MOD_NORMAL_ZTRANSLATE = 0x16,
        RMFIELD_LAYER_MOD_NORMAL_XSCALE = 0x17,
        RMFIELD_LAYER_MOD_NORMAL_YSCALE = 0x18,
        RMFIELD_LAYER_MOD_NORMAL_ZSCALE = 0x19,
        RMFIELD_LAYER_MOD_NORMAL_ORIGINPHASE = 0x1A,
        RMFIELD_LAYER_MOD_NORMAL_NORMALPHASE = 0x1B,
        RMFIELD_LAYER_MOD_DIFFUSE_R = 0x1C,
        RMFIELD_LAYER_MOD_DIFFUSE_G = 0x1D,
        RMFIELD_LAYER_MOD_DIFFUSE_B = 0x1E,
        RMFIELD_LAYER_MOD_DIFFUSE_A = 0x1F,
        RMFIELD_LAYER_MOD_UVTRANSLATE_UTRANSLATE = 0x20,
        RMFIELD_LAYER_MOD_UVTRANSLATE_VTRANSLATE = 0x21,
        RMFIELD_LAYER_MOD_UVROTATE_ROTATE = 0x22,
        RMFIELD_LAYER_MOD_UVSCALE_USCALE = 0x23,
        RMFIELD_LAYER_MOD_UVSCALE_VSCALE = 0x24,
    };
    public enum RenderPassType : uint {
        RenderPass_Default = 0x0,
        RenderPass_DirectionalLightDiffuseAndSpecular = 0x1,
        RenderPass_PointLightDiffuseAndSpecular = 0x2,
        RenderPass_PointLightDiffuseAndSpecularProjector = 0x3,
        RenderPass_AmbientLight_DirectionalLightDiffuseAndSpecular = 0x4,
        RenderPass_AmbientLight_PointLightDiffuseAndSpecular = 0x5,
        RenderPass_DistanceFog = 0x6,
        RenderPass_FixedFunctionGlow = 0x7,
        RenderPass_ShaderGlow = 0x8,
        RenderPass_LandscapeShadowMap = 0x9,
        RenderPass_AlphaBlend = 0xA,
        RenderPass_AL_0DL_0PL = 0xB,
        RenderPass_AL_0DL_1PL = 0xC,
        RenderPass_AL_0DL_2PL = 0xD,
        RenderPass_AL_0DL_3PL = 0xE,
        RenderPass_AL_0DL_4PL = 0xF,
        RenderPass_AL_0DL_5PL = 0x10,
        RenderPass_AL_0DL_6PL = 0x11,
        RenderPass_AL_0DL_7PL = 0x12,
        RenderPass_AL_0DL_8PL = 0x13,
        RenderPass_AL_1DL_0PL = 0x14,
        RenderPass_AL_1DL_1PL = 0x15,
        RenderPass_AL_1DL_2PL = 0x16,
        RenderPass_AL_1DL_3PL = 0x17,
        RenderPass_AL_1DL_4PL = 0x18,
        RenderPass_AL_1DL_5PL = 0x19,
        RenderPass_AL_1DL_6PL = 0x1A,
        RenderPass_AL_1DL_7PL = 0x1B,
        RenderPass_AL_0DL_0PL_Fog = 0x1C,
        RenderPass_AL_0DL_1PL_Fog = 0x1D,
        RenderPass_AL_0DL_2PL_Fog = 0x1E,
        RenderPass_AL_0DL_3PL_Fog = 0x1F,
        RenderPass_AL_0DL_4PL_Fog = 0x20,
        RenderPass_AL_0DL_5PL_Fog = 0x21,
        RenderPass_AL_0DL_6PL_Fog = 0x22,
        RenderPass_AL_0DL_7PL_Fog = 0x23,
        RenderPass_AL_0DL_8PL_Fog = 0x24,
        RenderPass_AL_1DL_0PL_Fog = 0x25,
        RenderPass_AL_1DL_1PL_Fog = 0x26,
        RenderPass_AL_1DL_2PL_Fog = 0x27,
        RenderPass_AL_1DL_3PL_Fog = 0x28,
        RenderPass_AL_1DL_4PL_Fog = 0x29,
        RenderPass_AL_1DL_5PL_Fog = 0x2A,
        RenderPass_AL_1DL_6PL_Fog = 0x2B,
        RenderPass_AL_1DL_7PL_Fog = 0x2C,
        RenderPass_MaxPasses = 0x2D,
        RenderPass_Invalid = 0x2E,
    };
    public enum TargetStatus : uint {
        Undef_TargetStatus = 0x0,
        Ok_TargetStatus = 0x1,
        ExitWorld_TargetStatus = 0x2,
        Teleported_TargetStatus = 0x3,
        Contained_TargetStatus = 0x4,
        Parented_TargetStatus = 0x5,
        TimedOut_TargetStatus = 0x6,
        FORCE_TargetStatus_32_BIT = 0x7FFFFFFF,
    };
    public enum StatType : uint {
        Undef_StatType = 0x0,
        Int_StatType = 0x1,
        Float_StatType = 0x2,
        Position_StatType = 0x3,
        Skill_StatType = 0x4,
        String_StatType = 0x5,
        DataID_StatType = 0x6,
        InstanceID_StatType = 0x7,
        DID_StatType = 0x6,
        IID_StatType = 0x7,
        Attribute_StatType = 0x8,
        Attribute_2nd_StatType = 0x9,
        BodyDamageValue_StatType = 0xA,
        BodyDamageVariance_StatType = 0xB,
        BodyArmorValue_StatType = 0xC,
        Bool_StatType = 0xD,
        Int64_StatType = 0xE,
        Num_StatTypes = 0xF,
    };

    public enum charError : uint {
        CHAR_ERROR_UNDEF = 0x0,
        CHAR_ERROR_LOGON = 0x1,
        CHAR_ERROR_LOGGED_ON = 0x2,
        CHAR_ERROR_ACCOUNT_LOGON = 0x3,
        CHAR_ERROR_SERVER_CRASH = 0x4,
        CHAR_ERROR_LOGOFF = 0x5,
        CHAR_ERROR_DELETE = 0x6,
        CHAR_ERROR_NO_PREMADE = 0x7,
        CHAR_ERROR_ACCOUNT_IN_USE = 0x8,
        CHAR_ERROR_ACCOUNT_INVALID = 0x9,
        CHAR_ERROR_ACCOUNT_DOESNT_EXIST = 0xA,
        CHAR_ERROR_ENTER_GAME_GENERIC = 0xB,
        CHAR_ERROR_ENTER_GAME_STRESS_ACCOUNT = 0xC,
        CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD = 0xD,
        CHAR_ERROR_ENTER_GAME_PLAYER_ACCOUNT_MISSING = 0xE,
        CHAR_ERROR_ENTER_GAME_CHARACTER_NOT_OWNED = 0xF,
        CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD_SERVER = 0x10,
        CHAR_ERROR_ENTER_GAME_OLD_CHARACTER = 0x11,
        CHAR_ERROR_ENTER_GAME_CORRUPT_CHARACTER = 0x12,
        CHAR_ERROR_ENTER_GAME_START_SERVER_DOWN = 0x13,
        CHAR_ERROR_ENTER_GAME_COULDNT_PLACE_CHARACTER = 0x14,
        CHAR_ERROR_LOGON_SERVER_FULL = 0x15,
        CHAR_ERROR_CHARACTER_IS_BOOTED = 0x16,
        CHAR_ERROR_ENTER_GAME_CHARACTER_LOCKED = 0x17,
        CHAR_ERROR_SUBSCRIPTION_EXPIRED = 0x18,
        CHAR_ERROR_NUM_ERRORS = 0x19,
        FORCE_charError_32_BIT = 0x7FFFFFFF,
    };
    public enum SKILL_ADVANCEMENT_CLASS : uint {
        UNDEF_SKILL_ADVANCEMENT_CLASS = 0x0,
        UNTRAINED_SKILL_ADVANCEMENT_CLASS = 0x1,
        TRAINED_SKILL_ADVANCEMENT_CLASS = 0x2,
        SPECIALIZED_SKILL_ADVANCEMENT_CLASS = 0x3,
        NUM_SKILL_ADVANCEMENT_CLASSES = 0x4,
        FORCE_SKILL_ADVANCEMENT_CLASS_32_BIT = 0x7FFFFFFF,
    };
    public enum DAMAGE_TYPE : uint {
        UNDEF_DAMAGE_TYPE = 0x0,
        SLASH_DAMAGE_TYPE = 0x1,
        PIERCE_DAMAGE_TYPE = 0x2,
        BLUDGEON_DAMAGE_TYPE = 0x4,
        COLD_DAMAGE_TYPE = 0x8,
        FIRE_DAMAGE_TYPE = 0x10,
        ACID_DAMAGE_TYPE = 0x20,
        ELECTRIC_DAMAGE_TYPE = 0x40,
        HEALTH_DAMAGE_TYPE = 0x80,
        STAMINA_DAMAGE_TYPE = 0x100,
        MANA_DAMAGE_TYPE = 0x200,
        NETHER_DAMAGE_TYPE = 0x400,
        BASE_DAMAGE_TYPE = 0x10000000,
        FORCE_DAMAGE_TYPE_32_BIT = 0x7FFFFFFF,
    };
    public enum BODY_HEIGHT : uint {
        UNDEF_BODY_HEIGHT = 0x0,
        HIGH_BODY_HEIGHT = 0x1,
        MEDIUM_BODY_HEIGHT = 0x2,
        LOW_BODY_HEIGHT = 0x3,
        NUM_BODY_HEIGHTS = 0x4,
        FORCE_BODY_HEIGHT32_BIT = 0x7FFFFFFF,
    };
    public enum RegenerationType : uint {
        Undef_RegenerationType = 0x0,
        Destruction_RegenerationType = 0x1,
        PickUp_RegenerationType = 0x2,
        Death_RegenerationType = 0x4,
        FORCE_RegenerationType_32_BIT = 0x7FFFFFFF,
    };
    public enum RegenLocationType : uint {
        Undef_RegenLocationType = 0x0,
        OnTop_RegenLocationType = 0x1,
        Scatter_RegenLocationType = 0x2,
        Specific_RegenLocationType = 0x4,
        Contain_RegenLocationType = 0x8,
        Wield_RegenLocationType = 0x10,
        Shop_RegenLocationType = 0x20,
        Checkpoint_RegenLocationType = 0x38,
        Treasure_RegenLocationType = 0x40,
        OnTopTreasure_RegenLocationType = 0x41,
        ScatterTreasure_RegenLocationType = 0x42,
        SpecificTreasure_RegenLocationType = 0x44,
        ContainTreasure_RegenLocationType = 0x48,
        WieldTreasure_RegenLocationType = 0x50,
        ShopTreasure_RegenLocationType = 0x60,
        FORCE_RegenLocationType_32_BIT = 0x7FFFFFFF,
    };
    public enum SoundType : uint {
        Sound_Invalid = 0x0,
        Sound_Speak1 = 0x1,
        Sound_Random = 0x2,
        Sound_Attack1 = 0x3,
        Sound_Attack2 = 0x4,
        Sound_Attack3 = 0x5,
        Sound_SpecialAttack1 = 0x6,
        Sound_SpecialAttack2 = 0x7,
        Sound_SpecialAttack3 = 0x8,
        Sound_Damage1 = 0x9,
        Sound_Damage2 = 0xA,
        Sound_Damage3 = 0xB,
        Sound_Wound1 = 0xC,
        Sound_Wound2 = 0xD,
        Sound_Wound3 = 0xE,
        Sound_Death1 = 0xF,
        Sound_Death2 = 0x10,
        Sound_Death3 = 0x11,
        Sound_Grunt1 = 0x12,
        Sound_Grunt2 = 0x13,
        Sound_Grunt3 = 0x14,
        Sound_Oh1 = 0x15,
        Sound_Oh2 = 0x16,
        Sound_Oh3 = 0x17,
        Sound_Heave1 = 0x18,
        Sound_Heave2 = 0x19,
        Sound_Heave3 = 0x1A,
        Sound_Knockdown1 = 0x1B,
        Sound_Knockdown2 = 0x1C,
        Sound_Knockdown3 = 0x1D,
        Sound_Swoosh1 = 0x1E,
        Sound_Swoosh2 = 0x1F,
        Sound_Swoosh3 = 0x20,
        Sound_Thump1 = 0x21,
        Sound_Smash1 = 0x22,
        Sound_Scratch1 = 0x23,
        Sound_Spear = 0x24,
        Sound_Sling = 0x25,
        Sound_Dagger = 0x26,
        Sound_ArrowWhiz1 = 0x27,
        Sound_ArrowWhiz2 = 0x28,
        Sound_CrossbowPull = 0x29,
        Sound_CrossbowRelease = 0x2A,
        Sound_BowPull = 0x2B,
        Sound_BowRelease = 0x2C,
        Sound_ThrownWeaponRelease1 = 0x2D,
        Sound_ArrowLand = 0x2E,
        Sound_Collision = 0x2F,
        Sound_HitFlesh1 = 0x30,
        Sound_HitLeather1 = 0x31,
        Sound_HitChain1 = 0x32,
        Sound_HitPlate1 = 0x33,
        Sound_HitMissile1 = 0x34,
        Sound_HitMissile2 = 0x35,
        Sound_HitMissile3 = 0x36,
        Sound_Footstep1 = 0x37,
        Sound_Footstep2 = 0x38,
        Sound_Walk1 = 0x39,
        Sound_Dance1 = 0x3A,
        Sound_Dance2 = 0x3B,
        Sound_Dance3 = 0x3C,
        Sound_Hidden1 = 0x3D,
        Sound_Hidden2 = 0x3E,
        Sound_Hidden3 = 0x3F,
        Sound_Eat1 = 0x40,
        Sound_Drink1 = 0x41,
        Sound_Open = 0x42,
        Sound_Close = 0x43,
        Sound_OpenSlam = 0x44,
        Sound_CloseSlam = 0x45,
        Sound_Ambient1 = 0x46,
        Sound_Ambient2 = 0x47,
        Sound_Ambient3 = 0x48,
        Sound_Ambient4 = 0x49,
        Sound_Ambient5 = 0x4A,
        Sound_Ambient6 = 0x4B,
        Sound_Ambient7 = 0x4C,
        Sound_Ambient8 = 0x4D,
        Sound_Waterfall = 0x4E,
        Sound_LogOut = 0x4F,
        Sound_LogIn = 0x50,
        Sound_LifestoneOn = 0x51,
        Sound_AttribUp = 0x52,
        Sound_AttribDown = 0x53,
        Sound_SkillUp = 0x54,
        Sound_SkillDown = 0x55,
        Sound_HealthUp = 0x56,
        Sound_HealthDown = 0x57,
        Sound_ShieldUp = 0x58,
        Sound_ShieldDown = 0x59,
        Sound_EnchantUp = 0x5A,
        Sound_EnchantDown = 0x5B,
        Sound_VisionUp = 0x5C,
        Sound_VisionDown = 0x5D,
        Sound_Fizzle = 0x5E,
        Sound_Launch = 0x5F,
        Sound_Explode = 0x60,
        Sound_TransUp = 0x61,
        Sound_TransDown = 0x62,
        Sound_BreatheFlaem = 0x63,
        Sound_BreatheAcid = 0x64,
        Sound_BreatheFrost = 0x65,
        Sound_BreatheLightning = 0x66,
        Sound_Create = 0x67,
        Sound_Destroy = 0x68,
        Sound_Lockpicking = 0x69,
        Sound_UI_EnterPortal = 0x6A,
        Sound_UI_ExitPortal = 0x6B,
        Sound_UI_GeneralQuery = 0x6C,
        Sound_UI_GeneralError = 0x6D,
        Sound_UI_TransientMessage = 0x6E,
        Sound_UI_IconPickUp = 0x6F,
        Sound_UI_IconSuccessfulDrop = 0x70,
        Sound_UI_IconInvalid_Drop = 0x71,
        Sound_UI_ButtonPress = 0x72,
        Sound_UI_GrabSlider = 0x73,
        Sound_UI_ReleaseSlider = 0x74,
        Sound_UI_NewTargetSelected = 0x75,
        Sound_UI_Roar = 0x76,
        Sound_UI_Bell = 0x77,
        Sound_UI_Chant1 = 0x78,
        Sound_UI_Chant2 = 0x79,
        Sound_UI_DarkWhispers1 = 0x7A,
        Sound_UI_DarkWhispers2 = 0x7B,
        Sound_UI_DarkLaugh = 0x7C,
        Sound_UI_DarkWind = 0x7D,
        Sound_UI_DarkSpeech = 0x7E,
        Sound_UI_Drums = 0x7F,
        Sound_UI_GhostSpeak = 0x80,
        Sound_UI_Breathing = 0x81,
        Sound_UI_Howl = 0x82,
        Sound_UI_LostSouls = 0x83,
        Sound_UI_Squeal = 0x84,
        Sound_UI_Thunder1 = 0x85,
        Sound_UI_Thunder2 = 0x86,
        Sound_UI_Thunder3 = 0x87,
        Sound_UI_Thunder4 = 0x88,
        Sound_UI_Thunder5 = 0x89,
        Sound_UI_Thunder6 = 0x8A,
        Sound_RaiseTrait = 0x8B,
        Sound_WieldObject = 0x8C,
        Sound_UnwieldObject = 0x8D,
        Sound_ReceiveItem = 0x8E,
        Sound_PickUpItem = 0x8F,
        Sound_DropItem = 0x90,
        Sound_ResistSpell = 0x91,
        Sound_PicklockFail = 0x92,
        Sound_LockSuccess = 0x93,
        Sound_OpenFailDueToLock = 0x94,
        Sound_TriggerActivated = 0x95,
        Sound_SpellExpire = 0x96,
        Sound_ItemManaDepleted = 0x97,
        Sound_TriggerActivated1 = 0x98,
        Sound_TriggerActivated2 = 0x99,
        Sound_TriggerActivated3 = 0x9A,
        Sound_TriggerActivated4 = 0x9B,
        Sound_TriggerActivated5 = 0x9C,
        Sound_TriggerActivated6 = 0x9D,
        Sound_TriggerActivated7 = 0x9E,
        Sound_TriggerActivated8 = 0x9F,
        Sound_TriggerActivated9 = 0xA0,
        Sound_TriggerActivated10 = 0xA1,
        Sound_TriggerActivated11 = 0xA2,
        Sound_TriggerActivated12 = 0xA3,
        Sound_TriggerActivated13 = 0xA4,
        Sound_TriggerActivated14 = 0xA5,
        Sound_TriggerActivated15 = 0xA6,
        Sound_TriggerActivated16 = 0xA7,
        Sound_TriggerActivated17 = 0xA8,
        Sound_TriggerActivated18 = 0xA9,
        Sound_TriggerActivated19 = 0xAA,
        Sound_TriggerActivated20 = 0xAB,
        Sound_TriggerActivated21 = 0xAC,
        Sound_TriggerActivated22 = 0xAD,
        Sound_TriggerActivated23 = 0xAE,
        Sound_TriggerActivated24 = 0xAF,
        Sound_TriggerActivated25 = 0xB0,
        Sound_TriggerActivated26 = 0xB1,
        Sound_TriggerActivated27 = 0xB2,
        Sound_TriggerActivated28 = 0xB3,
        Sound_TriggerActivated29 = 0xB4,
        Sound_TriggerActivated30 = 0xB5,
        Sound_TriggerActivated31 = 0xB6,
        Sound_TriggerActivated32 = 0xB7,
        Sound_TriggerActivated33 = 0xB8,
        Sound_TriggerActivated34 = 0xB9,
        Sound_TriggerActivated35 = 0xBA,
        Sound_TriggerActivated36 = 0xBB,
        Sound_TriggerActivated37 = 0xBC,
        Sound_TriggerActivated38 = 0xBD,
        Sound_TriggerActivated39 = 0xBE,
        Sound_TriggerActivated40 = 0xBF,
        Sound_TriggerActivated41 = 0xC0,
        Sound_TriggerActivated42 = 0xC1,
        Sound_TriggerActivated43 = 0xC2,
        Sound_TriggerActivated44 = 0xC3,
        Sound_TriggerActivated45 = 0xC4,
        Sound_TriggerActivated46 = 0xC5,
        Sound_TriggerActivated47 = 0xC6,
        Sound_TriggerActivated48 = 0xC7,
        Sound_TriggerActivated49 = 0xC8,
        Sound_TriggerActivated50 = 0xC9,
        Sound_HealthDownVoid = 0xCA,
        Sound_RegenDownVoid = 0xCB,
        Sound_SkillDownVoid = 0xCC,
        NUM_SOUND_TYPES = 0xCD,
        FORCE_SoundType_32_BIT = 0x7FFFFFFF,
    };
    public enum PScriptType : uint {
        PS_Invalid = 0x0,
        PS_Test1 = 0x1,
        PS_Test2 = 0x2,
        PS_Test3 = 0x3,
        PS_Launch = 0x4,
        PS_Explode = 0x5,
        PS_AttribUpRed = 0x6,
        PS_AttribDownRed = 0x7,
        PS_AttribUpOrange = 0x8,
        PS_AttribDownOrange = 0x9,
        PS_AttribUpYellow = 0xA,
        PS_AttribDownYellow = 0xB,
        PS_AttribUpGreen = 0xC,
        PS_AttribDownGreen = 0xD,
        PS_AttribUpBlue = 0xE,
        PS_AttribDownBlue = 0xF,
        PS_AttribUpPurple = 0x10,
        PS_AttribDownPurple = 0x11,
        PS_SkillUpRed = 0x12,
        PS_SkillDownRed = 0x13,
        PS_SkillUpOrange = 0x14,
        PS_SkillDownOrange = 0x15,
        PS_SkillUpYellow = 0x16,
        PS_SkillDownYellow = 0x17,
        PS_SkillUpGreen = 0x18,
        PS_SkillDownGreen = 0x19,
        PS_SkillUpBlue = 0x1A,
        PS_SkillDownBlue = 0x1B,
        PS_SkillUpPurple = 0x1C,
        PS_SkillDownPurple = 0x1D,
        PS_SkillDownBlack = 0x1E,
        PS_HealthUpRed = 0x1F,
        PS_HealthDownRed = 0x20,
        PS_HealthUpBlue = 0x21,
        PS_HealthDownBlue = 0x22,
        PS_HealthUpYellow = 0x23,
        PS_HealthDownYellow = 0x24,
        PS_RegenUpRed = 0x25,
        PS_RegenDownREd = 0x26,
        PS_RegenUpBlue = 0x27,
        PS_RegenDownBlue = 0x28,
        PS_RegenUpYellow = 0x29,
        PS_RegenDownYellow = 0x2A,
        PS_ShieldUpRed = 0x2B,
        PS_ShieldDownRed = 0x2C,
        PS_ShieldUpOrange = 0x2D,
        PS_ShieldDownOrange = 0x2E,
        PS_ShieldUpYellow = 0x2F,
        PS_ShieldDownYellow = 0x30,
        PS_ShieldUpGreen = 0x31,
        PS_ShieldDownGreen = 0x32,
        PS_ShieldUpBlue = 0x33,
        PS_ShieldDownBlue = 0x34,
        PS_ShieldUpPurple = 0x35,
        PS_ShieldDownPurple = 0x36,
        PS_ShieldUpGrey = 0x37,
        PS_ShieldDownGrey = 0x38,
        PS_EnchantUpRed = 0x39,
        PS_EnchantDownRed = 0x3A,
        PS_EnchantUpOrange = 0x3B,
        PS_EnchantDownOrange = 0x3C,
        PS_EnchantUpYellow = 0x3D,
        PS_EnchantDownYellow = 0x3E,
        PS_EnchantUpGreen = 0x3F,
        PS_EnchantDownGreen = 0x40,
        PS_EnchantUpBlue = 0x41,
        PS_EnchantDownBlue = 0x42,
        PS_EnchantUpPurple = 0x43,
        PS_EnchantDownPurple = 0x44,
        PS_VitaeUpWhite = 0x45,
        PS_VitaeDownBlack = 0x46,
        PS_VisionUpWhite = 0x47,
        PS_VisionDownBlack = 0x48,
        PS_SwapHealth_Red_To_Yellow = 0x49,
        PS_SwapHealth_Red_To_Blue = 0x4A,
        PS_SwapHealth_Yellow_To_Red = 0x4B,
        PS_SwapHealth_Yellow_To_Blue = 0x4C,
        PS_SwapHealth_Blue_To_Red = 0x4D,
        PS_SwapHealth_Blue_To_Yellow = 0x4E,
        PS_TransUpWhite = 0x4F,
        PS_TransDownBlack = 0x50,
        PS_Fizzle = 0x51,
        PS_PortalEntry = 0x52,
        PS_PortalExit = 0x53,
        PS_BreatheFlame = 0x54,
        PS_BreatheFrost = 0x55,
        PS_BreatheAcid = 0x56,
        PS_BreatheLightning = 0x57,
        PS_Create = 0x58,
        PS_Destroy = 0x59,
        PS_ProjectileCollision = 0x5A,
        PS_SplatterLowLeftBack = 0x5B,
        PS_SplatterLowLeftFront = 0x5C,
        PS_SplatterLowRightBack = 0x5D,
        PS_SplatterLowRightFront = 0x5E,
        PS_SplatterMidLeftBack = 0x5F,
        PS_SplatterMidLeftFront = 0x60,
        PS_SplatterMidRightBack = 0x61,
        PS_SplatterMidRightFront = 0x62,
        PS_SplatterUpLeftBack = 0x63,
        PS_SplatterUpLeftFront = 0x64,
        PS_SplatterUpRightBack = 0x65,
        PS_SplatterUpRightFront = 0x66,
        PS_SparkLowLeftBack = 0x67,
        PS_SparkLowLeftFront = 0x68,
        PS_SparkLowRightBack = 0x69,
        PS_SparkLowRightFront = 0x6A,
        PS_SparkMidLeftBack = 0x6B,
        PS_SparkMidLeftFront = 0x6C,
        PS_SparkMidRightBack = 0x6D,
        PS_SparkMidRightFront = 0x6E,
        PS_SparkUpLeftBack = 0x6F,
        PS_SparkUpLeftFront = 0x70,
        PS_SparkUpRightBack = 0x71,
        PS_SparkUpRightFront = 0x72,
        PS_PortalStorm = 0x73,
        PS_Hide = 0x74,
        PS_UnHide = 0x75,
        PS_Hidden = 0x76,
        PS_DisappearDestroy = 0x77,
        SpecialState1 = 0x78,
        SpecialState2 = 0x79,
        SpecialState3 = 0x7A,
        SpecialState4 = 0x7B,
        SpecialState5 = 0x7C,
        SpecialState6 = 0x7D,
        SpecialState7 = 0x7E,
        SpecialState8 = 0x7F,
        SpecialState9 = 0x80,
        SpecialState0 = 0x81,
        SpecialStateRed = 0x82,
        SpecialStateOrange = 0x83,
        SpecialStateYellow = 0x84,
        SpecialStateGreen = 0x85,
        SpecialStateBlue = 0x86,
        SpecialStatePurple = 0x87,
        SpecialStateWhite = 0x88,
        SpecialStateBlack = 0x89,
        PS_LevelUp = 0x8A,
        PS_EnchantUpGrey = 0x8B,
        PS_EnchantDownGrey = 0x8C,
        PS_WeddingBliss = 0x8D,
        PS_EnchantUpWhite = 0x8E,
        PS_EnchantDownWhite = 0x8F,
        PS_CampingMastery = 0x90,
        PS_CampingIneptitude = 0x91,
        PS_DispelLife = 0x92,
        PS_DispelCreature = 0x93,
        PS_DispelAll = 0x94,
        PS_BunnySmite = 0x95,
        PS_BaelZharonSmite = 0x96,
        PS_WeddingSteele = 0x97,
        PS_RestrictionEffectBlue = 0x98,
        PS_RestrictionEffectGreen = 0x99,
        PS_RestrictionEffectGold = 0x9A,
        PS_LayingofHands = 0x9B,
        PS_AugmentationUseAttribute = 0x9C,
        PS_AugmentationUseSkill = 0x9D,
        PS_AugmentationUseResistances = 0x9E,
        PS_AugmentationUseOther = 0x9F,
        PS_BlackMadness = 0xA0,
        PS_AetheriaLevelUp = 0xA1,
        PS_AetheriaSurgeDestruction = 0xA2,
        PS_AetheriaSurgeProtection = 0xA3,
        PS_AetheriaSurgeRegeneration = 0xA4,
        PS_AetheriaSurgeAffliction = 0xA5,
        PS_AetheriaSurgeFestering = 0xA6,
        PS_HealthDownVoid = 0xA7,
        PS_RegenDownVoid = 0xA8,
        PS_SkillDownVoid = 0xA9,
        PS_DirtyFightingHealDebuff = 0xAA,
        PS_DirtyFightingAttackDebuff = 0xAB,
        PS_DirtyFightingDefenseDebuff = 0xAC,
        PS_DirtyFightingDamageOverTime = 0xAD,
        NUM_PSCRIPT_TYPES = 0xAE,
        FORCE_PScriptType_32_BIT = 0x7FFFFFFF,
    };
    public enum LandDefs__WaterType : uint {
        NOT_WATER = 0x0,
        PARTIALLY_WATER = 0x1,
        ENTIRELY_WATER = 0x2,
        FORCE_WaterType_32_BIT = 0x7FFFFFFF,
    };
    public enum LandDefs__Rotation : uint {
        ROT_0 = 0x0,
        ROT_90 = 0x1,
        ROT_180 = 0x2,
        ROT_270 = 0x3,
        FORCE_Rotation_32_BIT = 0x7FFFFFFF,
    };
    public enum LandDefs__PalType : uint {
        SWTerrain = 0x0,
        SETerrain = 0x1,
        NETerrain = 0x2,
        NWTerrain = 0x3,
        Road = 0x4,
        FORCE_PalType_32_BIT = 0x7FFFFFFF,
    };
    public enum LandDefs__TerrainType : uint {
        BarrenRock = 0x0,
        Grassland = 0x1,
        Ice = 0x2,
        LushGrass = 0x3,
        MarshSparseSwamp = 0x4,
        MudRichDirt = 0x5,
        ObsidianPlain = 0x6,
        PackedDirt = 0x7,
        PatchyDirt = 0x8,
        PatchyGrassland = 0x9,
        SandYellow = 0xA,
        SandGrey = 0xB,
        SandRockStrewn = 0xC,
        SedimentaryRock = 0xD,
        SemiBarrenRock = 0xE,
        Snow = 0xF,
        WaterRunning = 0x10,
        WaterStandingFresh = 0x11,
        WaterShallowSea = 0x12,
        WaterShallowStillSea = 0x13,
        WaterDeepSea = 0x14,
        Reserved21 = 0x15,
        Reserved22 = 0x16,
        Reserved23 = 0x17,
        Reserved24 = 0x18,
        Reserved25 = 0x19,
        Reserved26 = 0x1A,
        Reserved27 = 0x1B,
        Reserved28 = 0x1C,
        Reserved29 = 0x1D,
        Reserved30 = 0x1E,
        Reserved31 = 0x1F,
        RoadType = 0x20,
        FORCE_TerrainType_32_BIT = 0x7FFFFFFF,
    };
    public enum PhysicsDesc__PhysicsDescInfo : uint {
        CSetup = 0x1,
        MTABLE = 0x2,
        VELOCITY = 0x4,
        ACCELERATION = 0x8,
        OMEGA = 0x10,
        PARENT = 0x20,
        CHILDREN = 0x40,
        OBJSCALE = 0x80,
        FRICTION = 0x100,
        ELASTICITY = 0x200,
        TIMESTAMPS = 0x400,
        STABLE = 0x800,
        PETABLE = 0x1000,
        DEFAULT_SCRIPT = 0x2000,
        DEFAULT_SCRIPT_INTENSITY = 0x4000,
        POSITION = 0x8000,
        MOVEMENT = 0x10000,
        ANIMFRAME_ID = 0x20000,
        TRANSLUCENCY = 0x40000,
        FORCE_PhysicsDescInfo_32_BIT = 0x7FFFFFFF,
    }; public enum PhysicsObjHook__HookType : uint {
        CSetup = 0x1,
        MTABLE = 0x2,
        VELOCITY = 0x4,
        ACCELERATION = 0x8,
        OMEGA = 0x10,
        PARENT = 0x20,
        CHILDREN = 0x40,
        OBJSCALE = 0x80,
        FRICTION = 0x100,
        ELASTICITY = 0x200,
        TIMESTAMPS = 0x400,
        STABLE = 0x800,
        PETABLE = 0x1000,
        DEFAULT_SCRIPT = 0x2000,
        DEFAULT_SCRIPT_INTENSITY = 0x4000,
        POSITION = 0x8000,
        MOVEMENT = 0x10000,
        ANIMFRAME_ID = 0x20000,
        TRANSLUCENCY = 0x40000,
        FORCE_PhysicsDescInfo_32_BIT = 0x7FFFFFFF,
    };
    public enum MovementTypes__Type : uint {
        Invalid = 0x0,
        RawCommand = 0x1,
        InterpretedCommand = 0x2,
        StopRawCommand = 0x3,
        StopInterpretedCommand = 0x4,
        StopCompletely = 0x5,
        MoveToObject = 0x6,
        MoveToPosition = 0x7,
        TurnToObject = 0x8,
        TurnToHeading = 0x9,
        FORCE_Type_32_BIT = 0x7FFFFFFF,
    };
    public enum LandDefs__Direction : uint {
        IN_VIEWER_BLOCK = 0x0,
        NORTH_OF_VIEWER = 0x1,
        SOUTH_OF_VIEWER = 0x2,
        EAST_OF_VIEWER = 0x3,
        WEST_OF_VIEWER = 0x4,
        NORTHWEST_OF_VIEWER = 0x5,
        SOUTHWEST_OF_VIEWER = 0x6,
        NORTHEAST_OF_VIEWER = 0x7,
        SOUTHEAST_OF_VIEWER = 0x8,
        UNKNOWN = 0x9,
        FORCE_Direction_32_BIT = 0x7FFFFFFF,
    };
    public enum BoundingType : uint {
        OUTSIDE = 0x0,
        PARTIALLY_INSIDE = 0x1,
        ENTIRELY_INSIDE = 0x2,
        FORCE_BoundingType_32_BIT = 0x7FFFFFFF,
    };
    public enum SPHEREPATH__InsertType : uint {
        TRANSITION_INSERT = 0x0,
        PLACEMENT_INSERT = 0x1,
        INITIAL_PLACEMENT_INSERT = 0x2,
        FORCE_InsertType_32_BIT = 0x7FFFFFFF,
    };
    public enum Sidedness : uint {
        POSITIVE = 0x0,
        NEGATIVE = 0x1,
        IN_PLANE = 0x2,
        CROSSING = 0x3,
    };
    public enum NetBlobProcessedStatus : uint {
        NETBLOB_UNDEF_STATUS = 0x0,
        NETBLOB_PROCESSED_OK = 0x1,
        NETBLOB_OLD_INSTANCE = 0x2,
        NETBLOB_ERROR = 0x3,
        NETBLOB_QUEUED = 0x4,
        FORCE_NetBlobProcessedStatus_32_BIT = 0x7FFFFFFF,
    };
    public enum CameraTarget : uint {
        INVALID_TARGET = 0x0,
        LOOK_IN_DIRECTION = 0x1,
        LOOK_AT_OBJECT = 0x2,
        LOOK_AT_PIVOT = 0x4,
        ALIGN_WITH_PIVOT = 0x8,
        ALIGN_WITH_PLANE = 0x10,
        FORCE_CameraTarget_32_BIT = 0x7FFFFFFF,
    };
    public enum ObjectSelectStatus : uint {
        Invalid_OSS = 0x0,
        ObjectOnscreen_OSS = 0x1,
        ObjectOffscreen_OSS = 0x2,
        ObjectNotFound_OSS = 0x3,
        FORCE_ObjectSelectStatus_32_BIT = 0x7FFFFFFF,
    };
    public enum Method_CG : uint {
    };
    public enum AdvancedMethod_CG : uint {
    };
    public enum CG_VERIFICATION_RESPONSE : uint {
        UNDEF_CG_VERIFICATION_RESPONSE = 0x0,
        CG_VERIFICATION_RESPONSE_OK = 0x1,
        CG_VERIFICATION_RESPONSE_PENDING = 0x2,
        CG_VERIFICATION_RESPONSE_NAME_IN_USE = 0x3,
        CG_VERIFICATION_RESPONSE_NAME_BANNED = 0x4,
        CG_VERIFICATION_RESPONSE_CORRUPT = 0x5,
        CG_VERIFICATION_RESPONSE_DATABASE_DOWN = 0x6,
        CG_VERIFICATION_RESPONSE_ADMIN_PRIVILEGE_DENIED = 0x7,
        NUM_CG_VERIFICATION_RESPONSES = 0x8,
        FORCE_CG_VERIFICATION_RESPONSE_32_BIT = 0x7FFFFFFF,
    };
    public enum SKILL_CATEGORY : uint {
        UNDEF_SKILL_CATEGORY = 0x0,
        WEAPON_SKILL_CATEGORY = 0x1,
        NONWEAPON_SKILL_CATEGORY = 0x2,
        MAGIC_SKILL_CATEGORY = 0x3,
        NUM_SKILL_CATEGORIES = 0x4,
        FORCE_SKILL_CATEGORY_32_BIT = 0x7FFFFFFF,
    };
    public enum EnterChargen : uint {
        ENTER_NEW = 0x0,
        ENTER_CONTINUE = 0x1,
        ENTER_RANDOM = 0x2,
        FORCE_EnterChargen_32_BIT = 0x7FFFFFFF,
    };
    public enum UI_SLOT_SIDE : uint {
        SLOT_SIDE_NULL = 0x0,
        SLOT_SIDE_LEFT = 0x1,
        SLOT_SIDE_RIGHT = 0x2,
        FORCE_UI_SLOT_SIDE_32_BIT = 0x7FFFFFFF,
    };
    public enum SpellComponentCategory : uint {
        Scarab_SpellComponentCategory = 0x0,
        Herb_SpellComponentCategory = 0x1,
        PowderedGem_SpellComponentCategory = 0x2,
        AlchemicalSubstance_SpellComponentCategory = 0x3,
        Talisman_SpellComponentCategory = 0x4,
        Taper_SpellComponentCategory = 0x5,
        Pea_SpellComponentCategory = 0x6,
        Num_SpellComponentCategories = 0x7,
        Undef_SpellComponentCategory = 0x8,
        FORCE_SpellComponentCategory_32_BIT = 0x7FFFFFFF,
    };
    public enum SpellComponentType : uint {
        Undef_SpellComponentType = 0x0,
        Power_SpellComponentType = 0x1,
        Action_SpellComponentType = 0x2,
        ConceptPrefix_SpellComponentType = 0x3,
        ConceptSuffix_SpellComponentType = 0x4,
        Target_SpellComponentType = 0x5,
        Accent_SpellComponentType = 0x6,
        Pea_SpellComponentType = 0x7,
        FORCE_SpellComponentType_32_BIT = 0x7FFFFFFF,
    };
    public enum ClientCommunicationSystem__HelpType : uint {
        Summary_HelpType = 0x0,
        List_HelpType = 0x1,
        Detail_HelpType = 0x2,
    };
    public enum NodeNameType : uint {
        Null_NAMETYPE = 0xFF,
        PString_NAMETYPE = 0x0,
        UInt32_NAMETYPE = 0x1,
        Int32_NAMETYPE = 0x2,
        Double_NAMETYPE = 0x3,
        Float_NAMETYPE = 0x4,
        CellID_NAMETYPE = 0x5,
        InstanceID_NAMETYPE = 0x6,
        Bool_NAMETYPE = 0x7,
        Hex_NAMETYPE = 0x8,
        Binary_NAMETYPE = 0x9,
        BlockID_NAMETYPE = 0xA,
        UInt64_NAMETYPE = 0xB,
        Int64_NAMETYPE = 0xC,
        LongHex_NAMETYPE = 0xD,
        Guid_NAMETYPE = 0xE,
        NUM_NAMETYPES = 0xF,
    };

    public enum DropItemFlags : uint {
        DROPITEM_FLAGS_NONE = 0x0,
        DROPITEM_IS_CONTAINER = 0x1,
        DROPITEM_IS_VENDOR = 0x2,
        DROPITEM_IS_SHORTCUT = 0x4,
        DROPITEM_IS_SALVAGE = 0x8,
        DROPITEM_IS_ALIAS = 0xE,
        FORCE_DROPITEM_FLAGS_32_BIT = 0x7FFFFFFF,
    };
    public enum AllegianceVersion : uint {
        Undef_AllegianceVersion = 0x0,
        SpokespersonAdded_AllegianceVersion = 0x1,
        PoolsAdded_AllegianceVersion = 0x2,
        MotdAdded_AllegianceVersion = 0x3,
        ChatRoomIDAdded_AllegianceVersion = 0x4,
        BannedCharactersAdded_AllegianceVersion = 0x5,
        MultipleAllegianceOfficersAdded_AllegianceVersion = 0x6,
        Bindstones_AllegianceVersion = 0x7,
        AllegianceName_AllegianceVersion = 0x8,
        OfficersTitlesAdded_AllegianceVersion = 0x9,
        LockedState_AllegianceVersion = 0xA,
        ApprovedVassal_AllegianceVersion = 0xB,
        Newest_AllegianceVersion = 0xB,
        FORCE_AllegianceVersion_32_BIT = 0x7FFFFFFF,
    };

    public enum UIMode {
        None = 0,
        IntroUI = 0x10000001,
        DisconnectedUI = 0x10000002,
        DataPatchUI = 0x10000003,
        CreditsUI = 0x10000005,
        GamePlayUI = 0x10000008,
        EpilogueUI = 0x10000009,
        CharacterManagementUI = 0x1000000A,
        CharGenMainUI = 0x1000000B
    }


    public enum PlayerOption : uint {
        Invalid_PlayerOption = 0xFFFFFFFF,
        AutoRepeatAttack_PlayerOption = 0x0,
        IgnoreAllegianceRequests_PlayerOption = 0x1,
        IgnoreFellowshipRequests_PlayerOption = 0x2,
        IgnoreTradeRequests_PlayerOption = 0x3,
        DisableMostWeatherEffects_PlayerOption = 0x4,
        PersistentAtDay_PlayerOption = 0x5,
        AllowGive_PlayerOption = 0x6,
        ViewCombatTarget_PlayerOption = 0x7,
        ShowTooltips_PlayerOption = 0x8,
        UseDeception_PlayerOption = 0x9,
        ToggleRun_PlayerOption = 0xA,
        StayInChatMode_PlayerOption = 0xB,
        AdvancedCombatUI_PlayerOption = 0xC,
        AutoTarget_PlayerOption = 0xD,
        VividTargetingIndicator_PlayerOption = 0xE,
        FellowshipShareXP_PlayerOption = 0xF,
        AcceptLootPermits_PlayerOption = 0x10,
        FellowshipShareLoot_PlayerOption = 0x11,
        FellowshipAutoAcceptRequests_PlayerOption = 0x12,
        SideBySideVitals_PlayerOption = 0x13,
        CoordinatesOnRadar_PlayerOption = 0x14,
        SpellDuration_PlayerOption = 0x15,
        DisableHouseRestrictionEffects_PlayerOption = 0x16,
        DragItemOnPlayerOpensSecureTrade_PlayerOption = 0x17,
        DisplayAllegianceLogonNotifications_PlayerOption = 0x18,
        UseChargeAttack_PlayerOption = 0x19,
        UseCraftSuccessDialog_PlayerOption = 0x1A,
        HearAllegianceChat_PlayerOption = 0x1B,
        DisplayDateOfBirth_PlayerOption = 0x1C,
        DisplayAge_PlayerOption = 0x1D,
        DisplayChessRank_PlayerOption = 0x1E,
        DisplayFishingSkill_PlayerOption = 0x1F,
        DisplayNumberDeaths_PlayerOption = 0x20,
        DisplayTimeStamps_PlayerOption = 0x21,
        SalvageMultiple_PlayerOption = 0x22,
        HearGeneralChat_PlayerOption = 0x23,
        HearTradeChat_PlayerOption = 0x24,
        HearLFGChat_PlayerOption = 0x25,
        HearRoleplayChat_PlayerOption = 0x26,
        AppearOffline_PlayerOption = 0x27,
        DisplayNumberCharacterTitles_PlayerOption = 0x28,
        MainPackPreferred_PlayerOption = 0x29,
        LeadMissileTargets_PlayerOption = 0x2A,
        UseFastMissiles_PlayerOption = 0x2B,
        FilterLanguage_PlayerOption = 0x2C,
        ConfirmVolatileRareUse_PlayerOption = 0x2D,
        HearSocietyChat_PlayerOption = 0x2E,
        ShowHelm_PlayerOption = 0x2F,
        DisableDistanceFog_PlayerOption = 0x30,
        UseMouseTurning_PlayerOption = 0x31,
        ShowCloak_PlayerOption = 0x32,
        LockUI_PlayerOption = 0x33,
        TotalNumberOfPlayerOptions_PlayerOption = 0x34,
    };



























}
*/